In [1]:
import numpy as np
import matplotlib.pylab as plt
import pandas as pd
from sklearn.datasets import load_iris

# 1. Basic Loading and Creations

In [2]:
#load iris data
iris = load_iris()

#peek into dataframe
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

### 1.1. Vectors

In [7]:
#first record
print(iris.data[0, :]) #same as iris.data[0]
#second record
print(iris.data[1, :]) #same as iris.data[1]

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]


In [10]:
#represent first two records as numpy vectors
x1_v1 = np.array([[5.1], [3.5], [1.4], [0.2]])
x2_v1 = np.array([[4.9], [3.0], [1.4], [0.2]])

#using reshape function
x1_v2 = np.reshape(iris.data[0], (4, 1))
x2_v2 = np.reshape(iris.data[1], (4, 1))

print(x1_v1)
print("======")
print(x1_v2)

[[5.1]
 [3.5]
 [1.4]
 [0.2]]
[[5.1]
 [3.5]
 [1.4]
 [0.2]]


### 1.2 Matrix

In [19]:
#create matrix using the first two rows of iris dataset
X = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])
print("shape: " + str(X.shape))
print("ndim: " + str(X.ndim))
print(X)

shape: (2, 4)
ndim: 2
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]


# 2. Matrix Types

* Vectors
    * Zero vectors
    * One vectors
* Matrix
    * Transpose matrix
    * Diagonoal matrix
    * Identity matrix
    * Symmetric matrix

### 2.1 Zero and One Vectors

In [38]:
#zero vector
zeros = np.zeros((3, 1))
ones = np.ones((3, 1))

print("zeros : ")
print(zeros)
print("====")
print("ones : ")
print(ones)

zeros : 
[[0.]
 [0.]
 [0.]]
====
ones : 
[[1.]
 [1.]
 [1.]]


### 2.2 Transpose Matrix

In [27]:
#create matrix
A = np.array([[11, 21], [12, 22], [13, 23]])
print("shape: " + str(A.shape))
print("ndim: " + str(A.ndim))
print(A)

shape: (3, 2)
ndim: 2
[[11 21]
 [12 22]
 [13 23]]


In [29]:
#transpose of matrix A
print("shape: " + str(A.T.shape))
print("ndim: " + str(A.T.ndim))
print(A.T)

shape: (2, 3)
ndim: 2
[[11 12 13]
 [21 22 23]]


* Practice Problems
    * Find transpose of matrix X from iris dataset (matrix consisting of the first two rows of the dataset)
    * Find transpose of transpose of matrix X
        * We get the original matrix X

In [34]:
#find transpose
print("transpose X : ")
print(X.T)

transpose X : 
[[5.1 4.9]
 [3.5 3. ]
 [1.4 1.4]
 [0.2 0.2]]


In [35]:
#we get the original matrix X
print("transpose of transpose X : ")
print(X.T.T)

transpose of transpose X : 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]


### 2.3 Diagonal Matrix

* Matrix where off-diagonal entries are all zero

In [41]:
diag = np.diag([1, 2, 3])
diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### 2.4 Identity Matrix

* Two functions
    * **identity**
    * **eye**

In [42]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 3. Operations Of Vectors

* Dot products of vectors and matrices

$\vec{x} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$

$\vec{y} = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}$

### 3.1 Vectors as 2-D Ndarrays

In [52]:
#create ndarrays
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

In [51]:
np.dot(x.T, y)

array([[32]])

In [53]:
#same as above
x.T @ y

array([[32]])

### 3.2 Vectors as 1-D Ndarrays

* Can be written as 1-D Ndarrays

In [54]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

np.dot(x.T, y)

32

In [55]:
#same as below
np.dot(x, y)

32

### 3.3 Real World Example Using Inner(Dot) Product

* When and why do we use vector multiplications?
* Linear algebra is a tool that we use to handle data
* Example 1: Weighted Sum (가중합)
    * Say you want to purchase stocks of companies A, B, and C
        * Each stock costs 100, 80, and 50 dollars, respectively
        * We want to purchase each companies stocks 3, 4, and 5 units, respectively
        * You can use linear algebra, dot product, to solve how much money we need
* Example 2: Weighted Average (가중평균)
    * Finding a final grade that consists of two exams
        * Received 100 on the first, and 60 on the second exams
        * Each exam is worth 25% and 75%, respectively
* Example 3: Linear Regression
    * $\hat{y} = w_1x_1 + \cdot \cdot \cdot + w_nx_n$
    * $\hat{y} = w^Tx$
* Example 4: Sum of Squares (제곱합)

#### 3.3.1 Solution

In [59]:
#create ndarrays
price = np.array([[100], [80], [50]])
quantity = np.array([[3], [4], [5]])

print("shape: " + str(price.shape))
print("ndim: " + str(price.ndim))
print(price)

print("===========")

print("shape: " + str(quantity.shape))
print("ndim: " + str(quantity.ndim))
print(quantity)

shape: (3, 1)
ndim: 2
[[100]
 [ 80]
 [ 50]]
shape: (3, 1)
ndim: 2
[[3]
 [4]
 [5]]


In [60]:
print(np.dot(price.T, quantity))
print(np.dot(quantity.T, price))

[[870]]
[[870]]


#### 3.3.2 Solution

In [61]:
scores = np.array([[100], [60]])
weight = np.array([[0.25], [0.75]])

In [63]:
print(np.dot(scores.T, weight))
print(np.dot(weight.T, scores))

[[70.]]
[[70.]]


# 4. Operations of Matrices

In [66]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])

print("Shape of A: " + str(A.shape))
print("Shape of B: " + str(B.shape))

np.dot(A, B)

Shape of A: (2, 3)
Shape of B: (3, 2)


array([[22, 28],
       [49, 64]])

In [68]:
C = np.array([[1, 2, 3]])
D = np.array([[4, 7], [5, 8], [6, 9]])

In [71]:
C.dot(D)

array([[32, 50]])

# 5. Characteristics of Matrices

* Signs (positive, negative) of Matrices
    * Positive definite
    * Positive semi-definite
* Size
    * Norm
    * Trace
        * Only used for square matrix (정방행렬)

### 5.1 Signs of Matrices
* Determining signs of matrix A. x refers to any **non-zero** vectors
    * Positive definite: when $x^TAx > 0$
    * Positive semi-definite: when $x^TAx >= 0$

### 5.2 Norm

* $\lVert A\rVert_p = (\sum_{i=1}^{N}\sum_{j=1}^{M} \lvert a_{ij}\rvert ^ p)^{1/p}$
* Adding all elements of matrix A powered by $p$ and then powering the reuslt by $1/p$
* Usually, we use $p=2$

In [81]:
A = np.array([[-4, -3, -2], [-1, 0, 1], [2, 3, 4]])
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [83]:
np.linalg.norm(A)

7.745966692414834

In [92]:
np.sum(A**2) ** 0.5

7.745966692414834

In [94]:
B = np.array([[-4, -3, -2], [-1, 0, 1], [2, 3, 4], [0, 1, -3]])
B

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4],
       [ 0,  1, -3]])

In [96]:
c = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
c

array([[ 2, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  2]])

# 6. Inverse Matrix

### 6.1 Calculate Inverse Matrix in Numpy

In [98]:
#define matrix
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 1, 1]
])

A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [100]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

### 6.2 Characteristics of Inverse Matrix

* $A^-1A = AA^-1 = I$

In [104]:
np.dot(A, A_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
np.dot(A_inv, A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])